# Generated by Django 6.1 on 2026-08-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transaction_transaction_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='statements_dir',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
