# Generated by Django 6.1 on 2026-08-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_account_statements_dir'),
    ]

    operations = [
        migrations.AddField(
            model_name='importfile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
