# Generated by Django 6.1 on 2026-08-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categoryrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='pattern',
            field=models.CharField(max_length=255),
        ),
    ]
