# Generated by Django 6.1 on 2026-08-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_categoryrule_max_amount_categoryrule_min_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='exclude_from_reports',
            field=models.BooleanField(default=False),
        ),
    ]
